#!/bin/bash -x
if grep --quiet "^mattockfs:" /etc/passwd; then
  #Use regular setup to install the code and most python dependencies.
  python ./setup.py build
  sudo python ./setup.py install 
  #The above seems to fail sometimes after updating a source file, running it twice seems to fix it, duno why yet
  python ./setup.py build
  sudo python ./setup.py install
  mkdir -p /usr/lib/mfmf/bin
  sudo cp modules/*.py /usr/lib/mfmf/bin/
  sudo cp -R etc/* /etc/
  if grep --quiet "^mfmf_009:" /etc/passwd; then
      echo "User mfmf_009 users exists already, skipping user creation" 
  else
      groupadd -r mfmf_grp
      sudo useradd mfmf_000 -g mfmf_grp -d /var/mattock/mnt
      sudo useradd mfmf_001 -g mfmf_grp -d /var/mattock/mnt
      sudo useradd mfmf_002 -g mfmf_grp -d /var/mattock/mnt
      sudo useradd mfmf_003 -g mfmf_grp -d /var/mattock/mnt
      sudo useradd mfmf_004 -g mfmf_grp -d /var/mattock/mnt
      sudo useradd mfmf_005 -g mfmf_grp -d /var/mattock/mnt
      sudo useradd mfmf_006 -g mfmf_grp -d /var/mattock/mnt
      sudo useradd mfmf_007 -g mfmf_grp -d /var/mattock/mnt
      sudo useradd mfmf_008 -g mfmf_grp -d /var/mattock/mnt
      sudo useradd mfmf_009 -g mfmf_grp -d /var/mattock/mnt
  fi
  echo "Creating example steem.json"
  sudo cp steem.json /etc/mfmf/
  sudo chmod 440 /etc/mfmf/steem.json
  sudo chown mfmf_009 /etc/mfmf/steem.json 
else
  echo "Install MattockFS first!"
fi
